version: 1.0.{build}
image: Ubuntu1604
configuration: Debug, Release
platform: Any CPU
nuget:
  project_feed: true
build:
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  include_nuget_references: true
  verbosity: minimal
